feat: add formatter

diff --git a/script/hdr b/script/hdr
--- a/script/hdr
+++ b/script/hdr
@@ -14,8 +14,8 @@ usage() {
 err() {
   local red
   local reset
-  red=$(tput setaf 1 2>/dev/null || echo '')
-  reset=$(tput sgr0 2>/dev/null || echo '')
+  red=$(tput setaf 1 2> /dev/null || echo '')
+  reset=$(tput sgr0 2> /dev/null || echo '')
   echo "${red}error${reset}: $1" >&2
   exit 1
 }
@@ -25,39 +25,39 @@ if [ $# -eq 0 ]; then
 fi
 
 case "$1" in
--h | --help)
-  usage
-  ;;
-on)
-  DISPLAY_ID=$(get_display_id)
-  if [ -z "$DISPLAY_ID" ]; then
-    err "No display found."
-  fi
+  -h | --help)
+    usage
+    ;;
+  on)
+    DISPLAY_ID=$(get_display_id)
+    if [ -z "$DISPLAY_ID" ]; then
+      err "No display found."
+    fi
 
-  displayplacer "id:$DISPLAY_ID mode:183"
-  if [ $? -eq 0 ]; then
-    echo "✓ HDR activated."
-  else
-    err "✗ HDR activation failed."
-  fi
-  exit 0
-  ;;
-off)
-  DISPLAY_ID=$(get_display_id)
-  if [ -z "$DISPLAY_ID" ]; then
-    err "No display found."
-  fi
+    displayplacer "id:$DISPLAY_ID mode:183"
+    if [ $? -eq 0 ]; then
+      echo "✓ HDR activated."
+    else
+      err "✗ HDR activation failed."
+    fi
+    exit 0
+    ;;
+  off)
+    DISPLAY_ID=$(get_display_id)
+    if [ -z "$DISPLAY_ID" ]; then
+      err "No display found."
+    fi
 
-  displayplacer "id:$DISPLAY_ID mode:180"
-  if [ $? -eq 0 ]; then
-    echo "✓ HDR deactivated."
-  else
-    err "✗ HDR deactivation failed."
-  fi
-  exit 0
-  ;;
-*)
-  echo "wrong parameters."
-  usage
-  ;;
+    displayplacer "id:$DISPLAY_ID mode:180"
+    if [ $? -eq 0 ]; then
+      echo "✓ HDR deactivated."
+    else
+      err "✗ HDR deactivation failed."
+    fi
+    exit 0
+    ;;
+  *)
+    echo "wrong parameters."
+    usage
+    ;;
 esac
